### ISSUE TITLE
Want to delete after parse

### ISSUE THREAD

**Issue by timedata** [JChord/reiko-parser#2]
Hi,

We upload our .apk to Temp directory then parse it with reiko-parser.
Then we proceed to our logic finaly jobs is done and we try to delete temp apk file.
But the parser stay open i think and temp file not removed. When we stop the node process then its removed.

Best Regards.

**Comment by dos1in** [comment]
Hi~@timedata may i have your code segment pls.

**Comment by timedata** [comment]
const parser = new apkParser(filePath, 'apk', { withIcon: false });

        new Promise((resolve) => {
            parser.parse((err, pkgInfo) => {
                if (err) {
                    Handlers.ThrowError(err);
                }

                return resolve(pkgInfo);
            });
        }).then((pkgInfo) => {
            // business logic

            fs.unlinkSync(filePath);

            // file is not deleted now
            // will be deleted after stop node process
        });

**Comment by JChord** [comment]
> ```
>     const parser = new apkParser(filePath, 'apk', { withIcon: false });
> 
>     new Promise((resolve) => {
>         parser.parse((err, pkgInfo) => {
>             if (err) {
>                 Handlers.ThrowError(err);
>             }
> 
>             return resolve(pkgInfo);
>         });
>     }).then((pkgInfo) => {
>         // business logic
> 
>         fs.unlinkSync(filePath);
> 
>         // file is not deleted now
>         // will be deleted after stop node process
>     });
> ```
```
fs.closeSync(filePath); // add this before delete

fs.unlinkSync(filePath);
```

**Comment by dos1in** [comment]
> ```
>     const parser = new apkParser(filePath, 'apk', { withIcon: false });
> 
>     new Promise((resolve) => {
>         parser.parse((err, pkgInfo) => {
>             if (err) {
>                 Handlers.ThrowError(err);
>             }
> 
>             return resolve(pkgInfo);
>         });
>     }).then((pkgInfo) => {
>         // business logic
> 
>         fs.unlinkSync(filePath);
> 
>         // file is not deleted now
>         // will be deleted after stop node process
>     });
> ```

sry, can't reproduce the issue, try to use `fs.closeSync(fd)` before delete file.

**Comment by timedata** [comment]
what is "fd" parameter? i dont have any FileDescriptor because i didnt use fs.openSync()

**Comment by dos1in** [comment]
> what is "fd" parameter? i dont have any FileDescriptor because i didnt use fs.openSync()

can you give a demo repo so that I can verify this bug.

**Comment by timedata** [comment]
> > what is "fd" parameter? i dont have any FileDescriptor because i didnt use fs.openSync()
> 
> can you give a demo repo so that I can verify this bug.

demo repo is here
https://github.com/timedata/parser-demo

**Comment by dos1in** [comment]
@timedata demo can delete file immediately, maybe you can put the delete operation into parser function, like this:
```
parser.parse((err, pkgInfo) => {
    if (err) {
        throw err;
    }

    // business with pkgInfo

    fs.unlinkSync('test.apk');
});
```

**Comment by timedata** [comment]
> @timedata demo can delete file immediately, maybe you can put the delete operation into parser function, like this:
> 
> ```
> parser.parse((err, pkgInfo) => {
>     if (err) {
>         throw err;
>     }
> 
>     // business with pkgInfo
> 
>     fs.unlinkSync('test.apk');
> });
> ```

Im tried, same result. File isn't deleting with fs.unlinkSync('test.apk') immediately. Its deleting when im killed node process.

**Comment by timedata** [comment]
im captured issue, you can watch this:
https://www.youtube.com/watch?v=CTvVxEaiWuI

**Comment by JChord** [comment]
fixed v1.0.2

**Comment by timedata** [comment]
Hi,
updated to v1.0.7 in parser-demo repository and problem is still here.

**Comment by dos1in** [comment]
sry, mac os works well, I will try on windows later.

**Comment by dos1in** [comment]
v1.0.8 fixed~
